### ISSUE TITLE
support ability to hide fields 

### ISSUE THREAD

**Issue by callmestech** [polyvariant/better-tostring#102]
Hey !
It would be great to add the ability to hide fields containing sensitive data

**Comment by mrobakowski** [comment]
This library intentionally avoids being customizable, see https://github.com/polyvariant/better-tostring#customization.

That being said, for sensitive data I would recommend the following pattern:

```scala
case class Secret[T](value: T) {
  override def toString: String = "***"
}

// your class containing sensitive data
case class Config(
  username: String,
  password: Secret[String]
)
```

The only real downside of this is that you have to type an additional `.value` here and there in your code. If you really don't like that, you can add an implicit conversion method, but then it's harder to see when and where the secret is unveiled, which can lead to accidental leaks of sensitive data into logs etc., so I wouldn't recommend doing that.
