### ISSUE TITLE
Change organization/artifact

### ISSUE THREAD

**Issue by kubukoz** [polyvariant/better-tostring#21]
to `"com.kubukoz.better-tostring" % "plugin" % ...` - this should enable sharing access to Sonatype for the entire group, and also gives us the possibility to add e.g. an `annotations` module in the future.

**Comment by mrobakowski** [comment]
Can you have hyphens in groupids? The convention is definitely to use the Java package naming convention, which disallows hyphens. But I don't know if that is enforced by the tooling.

**Comment by kubukoz** [comment]
so we're gonna go with `org.polyvariant` soon - if someone wants to prepare a PR for Scala Steward to handle the migration, it should go to https://github.com/scala-steward-org/scala-steward/blob/7217290ea3b5ae2daaf84c6d1cf40d2ce71f9b26/modules/core/src/main/resources/artifact-migrations.conf
