### ISSUE TITLE
Quotes around String

### ISSUE THREAD

**Issue by sideeffffect** [polyvariant/better-tostring#78]
Have you considered putting double quotes around `String`s? That would make the result closer to the Scala code, like
```scala
User(name = "Joe", age = 18).toString() // User(name = "Joe", age = 18)
```

Somthing analogous could be done for `Char`s.

**Comment by sideeffffect** [comment]
Let me ask from a different side: what would be the reason for _not_ using PPrint as the _default_ "backend" for the `better-tostring` compiler plugin?

> It's hard to tell when to stop

Sure, I get that point. Any stage seem good to stop at as any other stage. But the order of importance is probably this:
 1. `String` and `Char`
 2. Java's Date(Time)
 3. Java's and Scala's `Duration`
 4. What else is there?

**Comment by kubukoz** [comment]
I'm pretty sure PPrint would need to be added as a dependency by the users - we couldn't do that as a compiler plugin. That's the #1 reason.

IMO this plugin should be considered a slight improvement of the defaults, not a full-blown pretty-printing plugin.
